name: Example workflow for Ruby using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          command: test
          args: --sarif-file-output=snyk.sarif
      - name: Print the snyk sarif file
        run : cat snyk.sarif
      - name: Total security issues
        run : |
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
              echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
          
